// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lstixczbxvkegkhzioud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzdGl4Y3pieHZrZWdraHppb3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDQ0NDQsImV4cCI6MjA2NjY4MDQ0NH0.ktitZgapnxhwf5R8_I-8UsmplLcJ3muOvyR1b57JaWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);